M48
; DRILL file {KiCad (6.0.7)} date Thu Nov 10 16:48:43 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-10T16:48:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X186.609Y-176.537
X186.727Y-109.22
X254.046Y-109.227
X254.046Y-176.537
T0
M30
